### PR TITLE
Fix license_family

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by bgruening** [comment]
@nsoranzo it seems OSX just build fine: https://anaconda.org/conda-forge/r-hash/files

**Comment by nsoranzo** [comment]
Yes, the problem is that all recent builds for staged-recipes master branch have been cancelled or are failing, e.g. for r-hash https://travis-ci.org/conda-forge/staged-recipes/builds/264468416 .

**Comment by nsoranzo** [comment]
Sorry for the confusion, the `r-hash` build for osx was created 5 hours later than the Linux one and I wrongly assumed it was due to the cancelled TravisCI build of `staged-recipes` master branch. This is just a cosmetic change now and adds me and @bgruening as co-maintainers.

**Comment by ocefpaf** [comment]
Let's see if merging this triggers the bot to add you guys to the @conda-forge/r-hash team.

**Pull request merged**
